const NOTIFICATION_TYPES = require('./notificationTypes');

/**
 * 알림 종류 → 사용자가 끌 수 있는 카테고리
 *
 * 앱의 "알림 설정" 화면에 있는 스위치와 1:1로 대응한다.
 * 여기에 없는 타입은 카테고리가 없는 것으로 보고 그냥 보낸다 —
 * 새 타입을 추가했는데 매핑을 빠뜨렸을 때 조용히 안 가는 것보다,
 * 일단 가고 나중에 분류되는 편이 낫다.
 */
const NOTIFICATION_CATEGORY = {
  // 미션
  [NOTIFICATION_TYPES.MISSION_EXPIRED]: 'mission',
  [NOTIFICATION_TYPES.MISSION_ASSIGNED]: 'mission',
  [NOTIFICATION_TYPES.MISSION_NEW]: 'mission',
  [NOTIFICATION_TYPES.HIDDEN_MISSION_AVAILABLE]: 'mission',
  [NOTIFICATION_TYPES.SEASON_STARTED]: 'mission',
  [NOTIFICATION_TYPES.TUTORIAL_REWARD_AVAILABLE]: 'mission',
  [NOTIFICATION_TYPES.DETECTION_TEST_AVAILABLE]: 'mission',
  [NOTIFICATION_TYPES.REVIEW_REQUEST_THRESHOLD]: 'mission',

  // 리뷰
  [NOTIFICATION_TYPES.REVIEW_PUBLISHED]: 'review',
  [NOTIFICATION_TYPES.REVIEW_SUBMITTED]: 'review',
  [NOTIFICATION_TYPES.DISPUTE_FILED]: 'review',
  [NOTIFICATION_TYPES.DISPUTE_RESOLVED]: 'review',
  [NOTIFICATION_TYPES.DETECTION_TEST_RESULT]: 'review',

  // 정산
  [NOTIFICATION_TYPES.SETTLEMENT_COMPLETE]: 'settlement',
  [NOTIFICATION_TYPES.SETTLEMENT_FAILED]: 'settlement',

  // 마케팅 — 수신 동의를 받은 사람에게만
  [NOTIFICATION_TYPES.COMPETITION_ALERT]: 'marketing',
  [NOTIFICATION_TYPES.REFERRAL_REGISTERED]: 'marketing',
  [NOTIFICATION_TYPES.REFERRAL_REWARDED]: 'marketing',
};

/**
 * 설정과 무관하게 항상 보내는 알림.
 *
 * 계정 상태와 돈에 관한 통지는 사용자가 껐다고 안 보낼 수 없다.
 * 못 받았다는 이유로 자격이 정지되거나 정산이 막히면 그 손해는
 * "알림을 껐으니까"로 정당화되지 않는다.
 */
const ALWAYS_SEND = new Set([
  NOTIFICATION_TYPES.CERTIFICATION_SUSPENDED,
  NOTIFICATION_TYPES.RECERTIFICATION_DUE,
  NOTIFICATION_TYPES.CERTIFICATION_DAY_UNLOCKED,
  NOTIFICATION_TYPES.CERTIFICATION_COMPLETED,
  NOTIFICATION_TYPES.QUALITY_WARNING,
  NOTIFICATION_TYPES.COLLUSION_WARNING,
  NOTIFICATION_TYPES.ASSIGNMENT_BLOCKED,
  NOTIFICATION_TYPES.STEALTH_WARNING,
  NOTIFICATION_TYPES.SYSTEM,
]);

module.exports = { NOTIFICATION_CATEGORY, ALWAYS_SEND };
